set -x
FLAGS="-filetype=o -O0 -stat"
PATHS="-I ."

circle $PATHS $FLAGS bsls_alignedbuffer.t.cpp
circle $PATHS $FLAGS bsls_alignmentfromtype.t.cpp
circle $PATHS $FLAGS bsls_alignmentimp.t.cpp
circle $PATHS $FLAGS bsls_alignment.t.cpp
circle $PATHS $FLAGS bsls_alignmenttotype.t.cpp
circle $PATHS $FLAGS bsls_alignmentutil.t.cpp
circle $PATHS $FLAGS bsls_annotation.t.cpp
circle $PATHS $FLAGS bsls_assertimputil.t.cpp
circle $PATHS $FLAGS bsls_assert_macroreset.t.cpp
circle $PATHS $FLAGS bsls_assert.t.cpp
circle $PATHS $FLAGS bsls_asserttestexception.t.cpp
circle $PATHS $FLAGS bsls_asserttest_macroreset.t.cpp
circle $PATHS $FLAGS bsls_asserttest.t.cpp
circle $PATHS $FLAGS bsls_atomicoperations_all_all_clangintrinsics.t.cpp
circle $PATHS $FLAGS bsls_atomicoperations_all_all_gccintrinsics.t.cpp
circle $PATHS $FLAGS bsls_atomicoperations_arm_all_gcc.t.cpp
circle $PATHS $FLAGS bsls_atomicoperations_default.t.cpp
circle $PATHS $FLAGS bsls_atomicoperations_ia64_hp_acc.t.cpp
circle $PATHS $FLAGS bsls_atomicoperations_powerpc32_aix_xlc.t.cpp
circle $PATHS $FLAGS bsls_atomicoperations_powerpc64_aix_xlc.t.cpp
circle $PATHS $FLAGS bsls_atomicoperations_powerpc_aix_xlc_default.t.cpp
circle $PATHS $FLAGS bsls_atomicoperations_powerpc_all_gcc.t.cpp
circle $PATHS $FLAGS bsls_atomicoperations_sparc32_sun_cc.t.cpp
circle $PATHS $FLAGS bsls_atomicoperations_sparc64_sun_cc.t.cpp
circle $PATHS $FLAGS bsls_atomicoperations_sparc_sun_cc_default.t.cpp
circle $PATHS $FLAGS bsls_atomicoperations.t.cpp
circle $PATHS $FLAGS bsls_atomicoperations_x64_all_gcc.t.cpp
circle $PATHS $FLAGS bsls_atomicoperations_x64_win_msvc.t.cpp
circle $PATHS $FLAGS bsls_atomicoperations_x86_all_gcc.t.cpp
circle $PATHS $FLAGS bsls_atomicoperations_x86_win_msvc.t.cpp
circle $PATHS $FLAGS bsls_atomic.t.cpp
circle $PATHS $FLAGS bsls_blockgrowth.t.cpp
circle $PATHS $FLAGS bsls_bsldeprecationinformation.t.cpp
circle $PATHS $FLAGS bsls_bslexceptionutil.t.cpp
circle $PATHS $FLAGS bsls_bsllock.t.cpp
circle $PATHS $FLAGS bsls_bslonce.t.cpp
circle $PATHS $FLAGS bsls_bsltestutil.t.cpp
circle $PATHS $FLAGS bsls_buildtarget.t.cpp
circle $PATHS $FLAGS bsls_byteorder.t.cpp
circle $PATHS $FLAGS bsls_byteorderutil_impl.t.cpp
circle $PATHS $FLAGS bsls_byteorderutil.t.cpp
circle $PATHS $FLAGS bsls_compilerfeatures.t.cpp
circle $PATHS $FLAGS bsls_cpp11.t.cpp
circle $PATHS $FLAGS bsls_dbghelpdllimpl_windows.t.cpp
circle $PATHS $FLAGS bsls_deprecate.t.cpp
circle $PATHS $FLAGS bsls_exceptionutil.t.cpp
circle $PATHS $FLAGS bsls_ident.t.cpp
circle $PATHS $FLAGS bsls_int64.t.cpp
circle $PATHS $FLAGS bsls_keyword.t.cpp
circle $PATHS $FLAGS bsls_libraryfeatures.t.cpp
circle $PATHS $FLAGS bsls_linkcoercion.t.cpp
circle $PATHS $FLAGS bsls_logseverity.t.cpp
circle $PATHS $FLAGS bsls_log.t.cpp
circle $PATHS $FLAGS bsls_macroincrement.t.cpp
circle $PATHS $FLAGS bsls_macrorepeat.t.cpp
circle $PATHS $FLAGS bsls_nameof.t.cpp
circle $PATHS $FLAGS bsls_nativestd.t.cpp
circle $PATHS $FLAGS bsls_nullptr.t.cpp
circle $PATHS $FLAGS bsls_objectbuffer.t.cpp
circle $PATHS $FLAGS bsls_outputredirector.t.cpp
circle $PATHS $FLAGS bsls_performancehint.t.cpp
circle $PATHS $FLAGS bsls_platform.t.cpp
circle $PATHS $FLAGS bsls_platformutil.t.cpp
circle $PATHS $FLAGS bsls_pointercastutil.t.cpp
circle $PATHS $FLAGS bsls_protocoltest.t.cpp
circle $PATHS $FLAGS bsls_review_macroreset.t.cpp
circle $PATHS $FLAGS bsls_review.t.cpp
circle $PATHS $FLAGS bsls_spinlock.t.cpp
circle $PATHS $FLAGS bsls_stackaddressutil.t.cpp
circle $PATHS $FLAGS bsls_stopwatch.t.cpp
circle $PATHS $FLAGS bsls_systemclocktype.t.cpp
circle $PATHS $FLAGS bsls_systemtime.t.cpp
circle $PATHS $FLAGS bsls_timeinterval.t.cpp
circle $PATHS $FLAGS bsls_timeutil.t.cpp
circle $PATHS $FLAGS bsls_types.t.cpp
circle $PATHS $FLAGS bsls_unspecifiedbool.t.cpp
circle $PATHS $FLAGS bsls_util.t.cpp
