set -x
PATHS="-I ."
FLAGS="-filetype=o -O0 -stat -I ../../bsl/bsls -I ../balscm -I ../../bsl/bslscm -I ../../bsl/bsl+bslhdrs -I ../../bsl/bslstl -I ../../bdl/bdlb -I ../../bsl/bslim -I ../../bsl/bslma -I ../../bsl/bslmf -I ../../bsl/bslh -I ../../bdl/bdlsb -I ../../bdl/bdlscm -I ../../bsl/bsla -I ../../bsl/bslalg -I ../../bdl/bdlt -I ../../bsl/bslx -I ../../bsl/bsltf -I ../../bsl/bslstp -I ../../bsl/bslmt -I ../../bdl/bdlcc -I ../../bdl/bdls -I ../../bdl/bdlma -I ../../bdl/bdlf -I ../../bdl/bdlmt -I ../balb"

circle $PATHS $FLAGS ball_administration.t.cpp
circle $PATHS $FLAGS ball_asyncfileobserver.t.cpp
circle $PATHS $FLAGS ball_attributecontainerlist.t.cpp
circle $PATHS $FLAGS ball_attributecontainer.t.cpp
circle $PATHS $FLAGS ball_attributecontext.t.cpp
circle $PATHS $FLAGS ball_attribute.t.cpp
circle $PATHS $FLAGS ball_broadcastobserver.t.cpp
circle $PATHS $FLAGS ball_categorymanager.t.cpp
circle $PATHS $FLAGS ball_category.t.cpp
circle $PATHS $FLAGS ball_context.t.cpp
circle $PATHS $FLAGS ball_countingallocator.t.cpp
circle $PATHS $FLAGS ball_defaultattributecontainer.t.cpp
circle $PATHS $FLAGS ball_fileobserver2.t.cpp
circle $PATHS $FLAGS ball_fileobserver.t.cpp
circle $PATHS $FLAGS ball_filteringobserver.t.cpp
circle $PATHS $FLAGS ball_fixedsizerecordbuffer.t.cpp
circle $PATHS $FLAGS ball_logfilecleanerutil.t.cpp
circle $PATHS $FLAGS ball_loggercategoryutil.t.cpp
circle $PATHS $FLAGS ball_loggerfunctorpayloads.t.cpp
circle $PATHS $FLAGS ball_loggermanagerconfiguration.t.cpp
circle $PATHS $FLAGS ball_loggermanagerdefaults.t.cpp
circle $PATHS $FLAGS ball_loggermanager.t.cpp
circle $PATHS $FLAGS ball_log.t.cpp
circle $PATHS $FLAGS ball_logthrottle.t.cpp
circle $PATHS $FLAGS ball_multiplexobserver.t.cpp
circle $PATHS $FLAGS ball_observeradapter.t.cpp
circle $PATHS $FLAGS ball_observer.t.cpp
circle $PATHS $FLAGS ball_patternutil.t.cpp
circle $PATHS $FLAGS ball_predicateset.t.cpp
circle $PATHS $FLAGS ball_predicate.t.cpp
circle $PATHS $FLAGS ball_recordattributes.t.cpp
circle $PATHS $FLAGS ball_recordbuffer.t.cpp
circle $PATHS $FLAGS ball_recordstringformatter.t.cpp
circle $PATHS $FLAGS ball_record.t.cpp
circle $PATHS $FLAGS ball_ruleset.t.cpp
circle $PATHS $FLAGS ball_rule.t.cpp
circle $PATHS $FLAGS ball_scopedattributes.t.cpp
circle $PATHS $FLAGS ball_scopedattribute.t.cpp
circle $PATHS $FLAGS ball_severity.t.cpp
circle $PATHS $FLAGS ball_severityutil.t.cpp
circle $PATHS $FLAGS ball_streamobserver.t.cpp
circle $PATHS $FLAGS ball_testobserver.t.cpp
circle $PATHS $FLAGS ball_thresholdaggregate.t.cpp
circle $PATHS $FLAGS ball_transmission.t.cpp
circle $PATHS $FLAGS ball_userfields.t.cpp
circle $PATHS $FLAGS ball_userfieldtype.t.cpp
circle $PATHS $FLAGS ball_userfieldvalue.t.cpp
