set -x
PATHS="-I . -I ../bsls -I ../bslscm -I ../bslmf -I ../bslh -I ../bsla -I ../bslalg -I ../bslma -I ../bsltf"
FLAGS="-filetype=o -O0 -stat"

circle $PATHS $FLAGS bslstl_algorithmworkaround.t.cpp
circle $PATHS $FLAGS bslstl_allocator.t.cpp
circle $PATHS $FLAGS bslstl_allocatortraits.t.cpp
circle $PATHS $FLAGS bslstl_array.t.cpp
circle $PATHS $FLAGS bslstl_badweakptr.t.cpp
circle $PATHS $FLAGS bslstl_bidirectionaliterator.t.cpp
circle $PATHS $FLAGS bslstl_bidirectionalnodepool.t.cpp
circle $PATHS $FLAGS bslstl_bitset.t.cpp
circle $PATHS $FLAGS bslstl_boyermoorehorspoolsearcher.t.cpp
circle $PATHS $FLAGS bslstl_chrono.t.cpp
circle $PATHS $FLAGS bslstl_complex.t.cpp
circle $PATHS $FLAGS bslstl_defaultsearcher.t.cpp
circle $PATHS $FLAGS bslstl_deque.t.cpp
circle $PATHS $FLAGS bslstl_deque_test.t.cpp
circle $PATHS $FLAGS bslstl_equalto.t.cpp
circle $PATHS $FLAGS bslstl_errc.t.cpp
circle $PATHS $FLAGS bslstl_error.t.cpp
circle $PATHS $FLAGS bslstl_forwarditerator.t.cpp
circle $PATHS $FLAGS bslstl_function.t.cpp
circle $PATHS $FLAGS bslstl_hashtablebucketiterator.t.cpp
circle $PATHS $FLAGS bslstl_hashtableiterator.t.cpp
circle $PATHS $FLAGS bslstl_hashtable.t.cpp
circle $PATHS $FLAGS bslstl_hashtable_test.t.cpp
circle $PATHS $FLAGS bslstl_hash.t.cpp
circle $PATHS $FLAGS bslstl_iosfwd.t.cpp
circle $PATHS $FLAGS bslstl_iserrorcodeenum.t.cpp
circle $PATHS $FLAGS bslstl_iserrorconditionenum.t.cpp
circle $PATHS $FLAGS bslstl_istringstream.t.cpp
circle $PATHS $FLAGS bslstl_iterator.t.cpp
circle $PATHS $FLAGS bslstl_iteratorutil.t.cpp
circle $PATHS $FLAGS bslstl_list.t.cpp
circle $PATHS $FLAGS bslstl_list_test.t.cpp
circle $PATHS $FLAGS bslstl_mapcomparator.t.cpp
circle $PATHS $FLAGS bslstl_map.t.cpp
circle $PATHS $FLAGS bslstl_map_test.t.cpp
circle $PATHS $FLAGS bslstl_multimap.t.cpp
circle $PATHS $FLAGS bslstl_multimap_test.t.cpp
circle $PATHS $FLAGS bslstl_multiset.t.cpp
circle $PATHS $FLAGS bslstl_multiset_test.t.cpp
circle $PATHS $FLAGS bslstl_ostringstream.t.cpp
circle $PATHS $FLAGS bslstl_ownerless.t.cpp
circle $PATHS $FLAGS bslstl_pair.t.cpp
circle $PATHS $FLAGS bslstl_priorityqueue.t.cpp
circle $PATHS $FLAGS bslstl_queue.t.cpp
circle $PATHS $FLAGS bslstl_randomaccessiterator.t.cpp
circle $PATHS $FLAGS bslstl_referencewrapper.t.cpp
circle $PATHS $FLAGS bslstl_setcomparator.t.cpp
circle $PATHS $FLAGS bslstl_set.t.cpp
circle $PATHS $FLAGS bslstl_set_test.t.cpp
circle $PATHS $FLAGS bslstl_sharedptrallocateinplacerep.t.cpp
circle $PATHS $FLAGS bslstl_sharedptrallocateoutofplacerep.t.cpp
circle $PATHS $FLAGS bslstl_sharedptr.t.cpp
circle $PATHS $FLAGS bslstl_simplepool.t.cpp
circle $PATHS $FLAGS bslstl_stack.t.cpp
circle $PATHS $FLAGS bslstl_stdexceptutil.t.cpp
circle $PATHS $FLAGS bslstl_stringbuf.t.cpp
circle $PATHS $FLAGS bslstl_stringrefdata.t.cpp
circle $PATHS $FLAGS bslstl_stringref.t.cpp
circle $PATHS $FLAGS bslstl_stringstream.t.cpp
circle $PATHS $FLAGS bslstl_string.t.cpp
circle $PATHS $FLAGS bslstl_string_test.t.cpp
circle $PATHS $FLAGS bslstl_stringview.t.cpp
circle $PATHS $FLAGS bslstl_systemerror.t.cpp
circle $PATHS $FLAGS bslstl_treeiterator.t.cpp
circle $PATHS $FLAGS bslstl_treenodepool.t.cpp
circle $PATHS $FLAGS bslstl_treenode.t.cpp
circle $PATHS $FLAGS bslstl_typeindex.t.cpp
circle $PATHS $FLAGS bslstl_unorderedmapkeyconfiguration.t.cpp
circle $PATHS $FLAGS bslstl_unorderedmap.t.cpp
circle $PATHS $FLAGS bslstl_unorderedmap_test.t.cpp
circle $PATHS $FLAGS bslstl_unorderedmultimap.t.cpp
circle $PATHS $FLAGS bslstl_unorderedmultimap_test.t.cpp
circle $PATHS $FLAGS bslstl_unorderedmultiset.t.cpp
circle $PATHS $FLAGS bslstl_unorderedmultiset_test.t.cpp
circle $PATHS $FLAGS bslstl_unorderedsetkeyconfiguration.t.cpp
circle $PATHS $FLAGS bslstl_unorderedset.t.cpp
circle $PATHS $FLAGS bslstl_unorderedset_test.t.cpp
circle $PATHS $FLAGS bslstl_vector.t.cpp
circle $PATHS $FLAGS bslstl_vector_test.t.cpp
