set -x
PATHS="-I . -I ../bsls -I ../bslscm -I ../bslalg -I ../bslmf -I ../bsla -I ../bslh -I ../bslma"
FLAGS="-filetype=o -O0 -stat"

circle $PATHS $FLAGS bslstl_algorithmworkaround.cpp
circle $PATHS $FLAGS bslstl_allocator.cpp
circle $PATHS $FLAGS bslstl_allocatortraits.cpp
circle $PATHS $FLAGS bslstl_array.cpp
circle $PATHS $FLAGS bslstl_badweakptr.cpp
circle $PATHS $FLAGS bslstl_bidirectionaliterator.cpp
circle $PATHS $FLAGS bslstl_bidirectionalnodepool.cpp
circle $PATHS $FLAGS bslstl_bitset.cpp
circle $PATHS $FLAGS bslstl_boyermoorehorspoolsearcher.cpp
circle $PATHS $FLAGS bslstl_chrono.cpp
circle $PATHS $FLAGS bslstl_complex.cpp
circle $PATHS $FLAGS bslstl_defaultsearcher.cpp
circle $PATHS $FLAGS bslstl_deque.cpp
circle $PATHS $FLAGS bslstl_deque_test.cpp
circle $PATHS $FLAGS bslstl_equalto.cpp
circle $PATHS $FLAGS bslstl_errc.cpp
circle $PATHS $FLAGS bslstl_error.cpp
circle $PATHS $FLAGS bslstl_forwarditerator.cpp
circle $PATHS $FLAGS bslstl_function.cpp
circle $PATHS $FLAGS bslstl_hash.cpp
circle $PATHS $FLAGS bslstl_hashtablebucketiterator.cpp
circle $PATHS $FLAGS bslstl_hashtable.cpp
circle $PATHS $FLAGS bslstl_hashtableiterator.cpp
circle $PATHS $FLAGS bslstl_hashtable_test.cpp
circle $PATHS $FLAGS bslstl_iosfwd.cpp
circle $PATHS $FLAGS bslstl_iserrorcodeenum.cpp
circle $PATHS $FLAGS bslstl_iserrorconditionenum.cpp
circle $PATHS $FLAGS bslstl_istringstream.cpp
circle $PATHS $FLAGS bslstl_iterator.cpp
circle $PATHS $FLAGS bslstl_iteratorutil.cpp
circle $PATHS $FLAGS bslstl_list.cpp
circle $PATHS $FLAGS bslstl_list_test.cpp
circle $PATHS $FLAGS bslstl_mapcomparator.cpp
circle $PATHS $FLAGS bslstl_map.cpp
circle $PATHS $FLAGS bslstl_map_test.cpp
circle $PATHS $FLAGS bslstl_multimap.cpp
circle $PATHS $FLAGS bslstl_multimap_test.cpp
circle $PATHS $FLAGS bslstl_multiset.cpp
circle $PATHS $FLAGS bslstl_multiset_test.cpp
circle $PATHS $FLAGS bslstl_ostringstream.cpp
circle $PATHS $FLAGS bslstl_ownerless.cpp
circle $PATHS $FLAGS bslstl_pair.cpp
circle $PATHS $FLAGS bslstl_priorityqueue.cpp
circle $PATHS $FLAGS bslstl_queue.cpp
circle $PATHS $FLAGS bslstl_randomaccessiterator.cpp
circle $PATHS $FLAGS bslstl_ratio.cpp
circle $PATHS $FLAGS bslstl_referencewrapper.cpp
circle $PATHS $FLAGS bslstl_setcomparator.cpp
circle $PATHS $FLAGS bslstl_set.cpp
circle $PATHS $FLAGS bslstl_set_test.cpp
circle $PATHS $FLAGS bslstl_sharedptrallocateinplacerep.cpp
circle $PATHS $FLAGS bslstl_sharedptrallocateoutofplacerep.cpp
circle $PATHS $FLAGS bslstl_sharedptr.cpp
circle $PATHS $FLAGS bslstl_simplepool.cpp
circle $PATHS $FLAGS bslstl_stack.cpp
circle $PATHS $FLAGS bslstl_stdexceptutil.cpp
circle $PATHS $FLAGS bslstl_stringbuf.cpp
circle $PATHS $FLAGS bslstl_string.cpp
circle $PATHS $FLAGS bslstl_stringref.cpp
circle $PATHS $FLAGS bslstl_stringrefdata.cpp
circle $PATHS $FLAGS bslstl_stringstream.cpp
circle $PATHS $FLAGS bslstl_string_test.cpp
circle $PATHS $FLAGS bslstl_stringview.cpp
circle $PATHS $FLAGS bslstl_systemerror.cpp
circle $PATHS $FLAGS bslstl_treeiterator.cpp
circle $PATHS $FLAGS bslstl_treenode.cpp
circle $PATHS $FLAGS bslstl_treenodepool.cpp
circle $PATHS $FLAGS bslstl_typeindex.cpp
circle $PATHS $FLAGS bslstl_unorderedmap.cpp
circle $PATHS $FLAGS bslstl_unorderedmapkeyconfiguration.cpp
circle $PATHS $FLAGS bslstl_unorderedmap_test.cpp
circle $PATHS $FLAGS bslstl_unorderedmultimap.cpp
circle $PATHS $FLAGS bslstl_unorderedmultimap_test.cpp
circle $PATHS $FLAGS bslstl_unorderedmultiset.cpp
circle $PATHS $FLAGS bslstl_unorderedmultiset_test.cpp
circle $PATHS $FLAGS bslstl_unorderedset.cpp
circle $PATHS $FLAGS bslstl_unorderedsetkeyconfiguration.cpp
circle $PATHS $FLAGS bslstl_unorderedset_test.cpp
circle $PATHS $FLAGS bslstl_vector.cpp
circle $PATHS $FLAGS bslstl_vector_test.cpp
