set -x
FLAGS="-filetype=o -O0 -stat"
PATHS="-I . -I ../bsls -I ../bslscm -I ../bsla"

circle $FLAGS $PATHS bslmf_addconst.t.cpp
circle $FLAGS $PATHS bslmf_addcv.t.cpp
circle $FLAGS $PATHS bslmf_addlvaluereference.t.cpp
circle $FLAGS $PATHS bslmf_addpointer.t.cpp
circle $FLAGS $PATHS bslmf_addreference.t.cpp
circle $FLAGS $PATHS bslmf_addrvaluereference.t.cpp
circle $FLAGS $PATHS bslmf_addvolatile.t.cpp
circle $FLAGS $PATHS bslmf_allocatorargt.t.cpp
circle $FLAGS $PATHS bslmf_arraytopointer.t.cpp
circle $FLAGS $PATHS bslmf_assert.t.cpp
circle $FLAGS $PATHS bslmf_conditional.t.cpp
circle $FLAGS $PATHS bslmf_decay.t.cpp
circle $FLAGS $PATHS bslmf_detectnestedtrait.t.cpp
circle $FLAGS $PATHS bslmf_enableif.t.cpp
circle $FLAGS $PATHS bslmf_forwardingtype.t.cpp
circle $FLAGS $PATHS bslmf_functionpointertraits.t.cpp
circle $FLAGS $PATHS bslmf_haspointersemantics.t.cpp
circle $FLAGS $PATHS bslmf_if.t.cpp
circle $FLAGS $PATHS bslmf_integersequence.t.cpp
circle $FLAGS $PATHS bslmf_integralconstant.t.cpp
circle $FLAGS $PATHS bslmf_invokeresult.t.cpp
circle $FLAGS $PATHS bslmf_isarithmetic.t.cpp
circle $FLAGS $PATHS bslmf_isarray.t.cpp
circle $FLAGS $PATHS bslmf_isbitwiseequalitycomparable.t.cpp
circle $FLAGS $PATHS bslmf_isbitwisemoveable.t.cpp
circle $FLAGS $PATHS bslmf_isclass.t.cpp
circle $FLAGS $PATHS bslmf_isconst.t.cpp
circle $FLAGS $PATHS bslmf_isconvertible.t.cpp
circle $FLAGS $PATHS bslmf_isconvertibletoany.t.cpp
circle $FLAGS $PATHS bslmf_iscopyconstructible.t.cpp
circle $FLAGS $PATHS bslmf_isempty.t.cpp
circle $FLAGS $PATHS bslmf_isenum.t.cpp
circle $FLAGS $PATHS bslmf_isfloatingpoint.t.cpp
circle $FLAGS $PATHS bslmf_isfunction.t.cpp
circle $FLAGS $PATHS bslmf_isfundamental.t.cpp
circle $FLAGS $PATHS bslmf_isintegral.t.cpp
circle $FLAGS $PATHS bslmf_islvaluereference.t.cpp
# circle $FLAGS $PATHS bslmf_ismemberfunctionpointer.t.cpp
# circle $FLAGS $PATHS bslmf_ismemberobjectpointer.t.cpp
# circle $FLAGS $PATHS bslmf_ismemberpointer.t.cpp
circle $FLAGS $PATHS bslmf_isnothrowmoveconstructible.t.cpp
circle $FLAGS $PATHS bslmf_ispair.t.cpp
circle $FLAGS $PATHS bslmf_ispointer.t.cpp
circle $FLAGS $PATHS bslmf_ispolymorphic.t.cpp
circle $FLAGS $PATHS bslmf_isreference.t.cpp
circle $FLAGS $PATHS bslmf_isrvaluereference.t.cpp
circle $FLAGS $PATHS bslmf_issame.t.cpp
circle $FLAGS $PATHS bslmf_istransparentpredicate.t.cpp
circle $FLAGS $PATHS bslmf_istriviallycopyable.t.cpp
circle $FLAGS $PATHS bslmf_istriviallydefaultconstructible.t.cpp
circle $FLAGS $PATHS bslmf_isvoid.t.cpp
circle $FLAGS $PATHS bslmf_isvolatile.t.cpp
circle $FLAGS $PATHS bslmf_makeintegersequence.t.cpp
circle $FLAGS $PATHS bslmf_matchanytype.t.cpp
circle $FLAGS $PATHS bslmf_matcharithmetictype.t.cpp
circle $FLAGS $PATHS bslmf_memberfunctionpointertraits.t.cpp
circle $FLAGS $PATHS bslmf_metaint.t.cpp
circle $FLAGS $PATHS bslmf_movableref.t.cpp
circle $FLAGS $PATHS bslmf_nestedtraitdeclaration.t.cpp
circle $FLAGS $PATHS bslmf_nil.t.cpp
circle $FLAGS $PATHS bslmf_nthparameter.t.cpp
circle $FLAGS $PATHS bslmf_removeconst.t.cpp
circle $FLAGS $PATHS bslmf_removecvq.t.cpp
circle $FLAGS $PATHS bslmf_removecv.t.cpp
circle $FLAGS $PATHS bslmf_removeextent.t.cpp
circle $FLAGS $PATHS bslmf_removepointer.t.cpp
circle $FLAGS $PATHS bslmf_removereference.t.cpp
circle $FLAGS $PATHS bslmf_removevolatile.t.cpp
circle $FLAGS $PATHS bslmf_resulttype.t.cpp
circle $FLAGS $PATHS bslmf_selecttrait.t.cpp
circle $FLAGS $PATHS bslmf_switch.t.cpp
circle $FLAGS $PATHS bslmf_tag.t.cpp
circle $FLAGS $PATHS bslmf_typelist.t.cpp
circle $FLAGS $PATHS bslmf_usesallocatorargt.t.cpp
circle $FLAGS $PATHS bslmf_usesallocator.t.cpp
circle $FLAGS $PATHS bslmf_util.t.cpp
circle $FLAGS $PATHS bslmf_voidtype.t.cpp
