set -x
PATHS="-I . -I ../bsls -I ../bslscm -I ../bslmf -I ../bsla"
FLAGS="-O0 -filetype=o -stat"

circle $PATHS $FLAGS bslmf_addconst.cpp
circle $PATHS $FLAGS bslmf_addcv.cpp
circle $PATHS $FLAGS bslmf_addlvaluereference.cpp
circle $PATHS $FLAGS bslmf_addpointer.cpp
circle $PATHS $FLAGS bslmf_addreference.cpp
circle $PATHS $FLAGS bslmf_addrvaluereference.cpp
circle $PATHS $FLAGS bslmf_addvolatile.cpp
circle $PATHS $FLAGS bslmf_allocatorargt.cpp
circle $PATHS $FLAGS bslmf_arraytopointer.cpp
circle $PATHS $FLAGS bslmf_assert.cpp
circle $PATHS $FLAGS bslmf_conditional.cpp
circle $PATHS $FLAGS bslmf_decay.cpp
circle $PATHS $FLAGS bslmf_detectnestedtrait.cpp
circle $PATHS $FLAGS bslmf_enableif.cpp
circle $PATHS $FLAGS bslmf_forwardingtype.cpp
circle $PATHS $FLAGS bslmf_functionpointertraits.cpp
circle $PATHS $FLAGS bslmf_haspointersemantics.cpp
circle $PATHS $FLAGS bslmf_if.cpp
circle $PATHS $FLAGS bslmf_integersequence.cpp
circle $PATHS $FLAGS bslmf_integralconstant.cpp
circle $PATHS $FLAGS bslmf_invokeresult.cpp
circle $PATHS $FLAGS bslmf_isarithmetic.cpp
circle $PATHS $FLAGS bslmf_isarray.cpp
circle $PATHS $FLAGS bslmf_isbitwiseequalitycomparable.cpp
circle $PATHS $FLAGS bslmf_isbitwisemoveable.cpp
circle $PATHS $FLAGS bslmf_isclass.cpp
circle $PATHS $FLAGS bslmf_isconst.cpp
circle $PATHS $FLAGS bslmf_isconvertible.cpp
circle $PATHS $FLAGS bslmf_isconvertibletoany.cpp
circle $PATHS $FLAGS bslmf_iscopyconstructible.cpp
circle $PATHS $FLAGS bslmf_isempty.cpp
circle $PATHS $FLAGS bslmf_isenum.cpp
circle $PATHS $FLAGS bslmf_isfloatingpoint.cpp
circle $PATHS $FLAGS bslmf_isfunction.cpp
circle $PATHS $FLAGS bslmf_isfundamental.cpp
circle $PATHS $FLAGS bslmf_isintegral.cpp
circle $PATHS $FLAGS bslmf_islvaluereference.cpp
circle $PATHS $FLAGS bslmf_ismemberfunctionpointer.cpp
circle $PATHS $FLAGS bslmf_ismemberobjectpointer.cpp
circle $PATHS $FLAGS bslmf_ismemberpointer.cpp
circle $PATHS $FLAGS bslmf_isnothrowmoveconstructible.cpp
circle $PATHS $FLAGS bslmf_ispair.cpp
circle $PATHS $FLAGS bslmf_ispointer.cpp
circle $PATHS $FLAGS bslmf_ispolymorphic.cpp
circle $PATHS $FLAGS bslmf_isreference.cpp
circle $PATHS $FLAGS bslmf_isrvaluereference.cpp
circle $PATHS $FLAGS bslmf_issame.cpp
circle $PATHS $FLAGS bslmf_istransparentpredicate.cpp
circle $PATHS $FLAGS bslmf_istriviallycopyable.cpp
circle $PATHS $FLAGS bslmf_istriviallydefaultconstructible.cpp
circle $PATHS $FLAGS bslmf_isvoid.cpp
circle $PATHS $FLAGS bslmf_isvolatile.cpp
circle $PATHS $FLAGS bslmf_makeintegersequence.cpp
circle $PATHS $FLAGS bslmf_matchanytype.cpp
circle $PATHS $FLAGS bslmf_matcharithmetictype.cpp
circle $PATHS $FLAGS bslmf_memberfunctionpointertraits.cpp
circle $PATHS $FLAGS bslmf_metaint.cpp
circle $PATHS $FLAGS bslmf_movableref.cpp
circle $PATHS $FLAGS bslmf_nestedtraitdeclaration.cpp
circle $PATHS $FLAGS bslmf_nil.cpp
circle $PATHS $FLAGS bslmf_nthparameter.cpp
circle $PATHS $FLAGS bslmf_removeconst.cpp
circle $PATHS $FLAGS bslmf_removecv.cpp
circle $PATHS $FLAGS bslmf_removecvq.cpp
circle $PATHS $FLAGS bslmf_removeextent.cpp
circle $PATHS $FLAGS bslmf_removepointer.cpp
circle $PATHS $FLAGS bslmf_removereference.cpp
circle $PATHS $FLAGS bslmf_removevolatile.cpp
circle $PATHS $FLAGS bslmf_resulttype.cpp
circle $PATHS $FLAGS bslmf_selecttrait.cpp
circle $PATHS $FLAGS bslmf_switch.cpp
circle $PATHS $FLAGS bslmf_tag.cpp
circle $PATHS $FLAGS bslmf_typelist.cpp
circle $PATHS $FLAGS bslmf_usesallocatorargt.cpp
circle $PATHS $FLAGS bslmf_usesallocator.cpp
circle $PATHS $FLAGS bslmf_util.cpp
circle $PATHS $FLAGS bslmf_voidtype.cpp
