set -x
PATHS="-I . -I ../bsls -I ../bslscm -I ../bslma -I ../bslim -I ../bsl+bslhdrs -I ../bslstl -I ../bslmf -I ../bslh -I ../bsla -I ../bslalg -I ../bsltf -I ../bslstp"
FLAGS="-filetype=o -O0 -stat"

circle $PATHS $FLAGS bslmt_barrier.t.cpp
circle $PATHS $FLAGS bslmt_conditionimpl_pthread.t.cpp
circle $PATHS $FLAGS bslmt_conditionimpl_win32.t.cpp
circle $PATHS $FLAGS bslmt_condition.t.cpp
circle $PATHS $FLAGS bslmt_configuration.t.cpp
circle $PATHS $FLAGS bslmt_entrypointfunctoradapter.t.cpp
circle $PATHS $FLAGS bslmt_fastpostsemaphoreimpl.t.cpp
circle $PATHS $FLAGS bslmt_fastpostsemaphore.t.cpp
circle $PATHS $FLAGS bslmt_latch.t.cpp
circle $PATHS $FLAGS bslmt_lockguard.t.cpp
circle $PATHS $FLAGS bslmt_meteredmutex.t.cpp
circle $PATHS $FLAGS bslmt_mutexassert.t.cpp
circle $PATHS $FLAGS bslmt_muteximpl_pthread.t.cpp
circle $PATHS $FLAGS bslmt_muteximpl_win32.t.cpp
circle $PATHS $FLAGS bslmt_mutex.t.cpp
circle $PATHS $FLAGS bslmt_once.t.cpp
circle $PATHS $FLAGS bslmt_platform.t.cpp
circle $PATHS $FLAGS bslmt_qlock.t.cpp
circle $PATHS $FLAGS bslmt_readerwriterlockassert.t.cpp
circle $PATHS $FLAGS bslmt_readerwriterlock.t.cpp
circle $PATHS $FLAGS bslmt_readerwritermuteximpl.t.cpp
circle $PATHS $FLAGS bslmt_readerwritermutex.t.cpp
circle $PATHS $FLAGS bslmt_readlockguard.t.cpp
circle $PATHS $FLAGS bslmt_recursivemuteximpl_pthread.t.cpp
circle $PATHS $FLAGS bslmt_recursivemuteximpl_win32.t.cpp
circle $PATHS $FLAGS bslmt_recursivemutex.t.cpp
circle $PATHS $FLAGS bslmt_rwmutex.t.cpp
circle $PATHS $FLAGS bslmt_saturatedtimeconversionimputil.t.cpp
circle $PATHS $FLAGS bslmt_semaphoreimpl_counted.t.cpp
circle $PATHS $FLAGS bslmt_semaphoreimpl_darwin.t.cpp
circle $PATHS $FLAGS bslmt_semaphoreimpl_pthread.t.cpp
circle $PATHS $FLAGS bslmt_semaphoreimpl_win32.t.cpp
circle $PATHS $FLAGS bslmt_semaphore.t.cpp
circle $PATHS $FLAGS bslmt_sluice.t.cpp
circle $PATHS $FLAGS bslmt_testutil.t.cpp
circle $PATHS $FLAGS bslmt_threadattributes.t.cpp
circle $PATHS $FLAGS bslmt_threadgroup.t.cpp
circle $PATHS $FLAGS bslmt_threadlocalvariable.t.cpp
circle $PATHS $FLAGS bslmt_threadutilimpl_pthread.t.cpp
circle $PATHS $FLAGS bslmt_threadutilimpl_win32.t.cpp
circle $PATHS $FLAGS bslmt_threadutil.t.cpp
circle $PATHS $FLAGS bslmt_throughputbenchmarkresult.t.cpp
circle $PATHS $FLAGS bslmt_throughputbenchmark.t.cpp
circle $PATHS $FLAGS bslmt_timedsemaphoreimpl_posixadv.t.cpp
circle $PATHS $FLAGS bslmt_timedsemaphoreimpl_pthread.t.cpp
circle $PATHS $FLAGS bslmt_timedsemaphoreimpl_win32.t.cpp
circle $PATHS $FLAGS bslmt_timedsemaphore.t.cpp
circle $PATHS $FLAGS bslmt_turnstile.t.cpp
circle $PATHS $FLAGS bslmt_writelockguard.t.cpp
