set -x
PATHS="-I . -I ../bsl+bslhdrs -I ../bsls -I ../bslstl -I ../bslstp -I ../bslalg -I ../bslh -I ../bslscm -I ../bslmf -I ../bsla -I ../bslma"
FLAGS="-O0 -filetype=o -stat"

circle $PATHS $FLAGS bslmt_barrier.cpp
circle $PATHS $FLAGS bslmt_condition.cpp
circle $PATHS $FLAGS bslmt_conditionimpl_pthread.cpp
circle $PATHS $FLAGS bslmt_conditionimpl_win32.cpp
circle $PATHS $FLAGS bslmt_configuration.cpp
circle $PATHS $FLAGS bslmt_entrypointfunctoradapter.cpp
circle $PATHS $FLAGS bslmt_fastpostsemaphore.cpp
circle $PATHS $FLAGS bslmt_fastpostsemaphoreimpl.cpp
circle $PATHS $FLAGS bslmt_latch.cpp
circle $PATHS $FLAGS bslmt_lockguard.cpp
circle $PATHS $FLAGS bslmt_meteredmutex.cpp
circle $PATHS $FLAGS bslmt_mutexassert.cpp
circle $PATHS $FLAGS bslmt_mutex.cpp
circle $PATHS $FLAGS bslmt_muteximpl_pthread.cpp
circle $PATHS $FLAGS bslmt_muteximpl_win32.cpp
circle $PATHS $FLAGS bslmt_once.cpp
circle $PATHS $FLAGS bslmt_platform.cpp
circle $PATHS $FLAGS bslmt_qlock.cpp
circle $PATHS $FLAGS bslmt_readerwriterlockassert.cpp
circle $PATHS $FLAGS bslmt_readerwriterlock.cpp
circle $PATHS $FLAGS bslmt_readerwritermutex.cpp
circle $PATHS $FLAGS bslmt_readerwritermuteximpl.cpp
circle $PATHS $FLAGS bslmt_readlockguard.cpp
circle $PATHS $FLAGS bslmt_recursivemutex.cpp
circle $PATHS $FLAGS bslmt_recursivemuteximpl_pthread.cpp
circle $PATHS $FLAGS bslmt_recursivemuteximpl_win32.cpp
circle $PATHS $FLAGS bslmt_rwmutex.cpp
circle $PATHS $FLAGS bslmt_saturatedtimeconversionimputil.cpp
circle $PATHS $FLAGS bslmt_semaphore.cpp
circle $PATHS $FLAGS bslmt_semaphoreimpl_counted.cpp
circle $PATHS $FLAGS bslmt_semaphoreimpl_darwin.cpp
circle $PATHS $FLAGS bslmt_semaphoreimpl_pthread.cpp
circle $PATHS $FLAGS bslmt_semaphoreimpl_win32.cpp
circle $PATHS $FLAGS bslmt_sluice.cpp
circle $PATHS $FLAGS bslmt_testutil.cpp
circle $PATHS $FLAGS bslmt_threadattributes.cpp
circle $PATHS $FLAGS bslmt_threadgroup.cpp
circle $PATHS $FLAGS bslmt_threadlocalvariable.cpp
circle $PATHS $FLAGS bslmt_threadutil.cpp
circle $PATHS $FLAGS bslmt_threadutilimpl_pthread.cpp
circle $PATHS $FLAGS bslmt_threadutilimpl_win32.cpp
circle $PATHS $FLAGS bslmt_throughputbenchmark.cpp
circle $PATHS $FLAGS bslmt_throughputbenchmarkresult.cpp
circle $PATHS $FLAGS bslmt_timedsemaphore.cpp
circle $PATHS $FLAGS bslmt_timedsemaphoreimpl_posixadv.cpp
circle $PATHS $FLAGS bslmt_timedsemaphoreimpl_pthread.cpp
circle $PATHS $FLAGS bslmt_timedsemaphoreimpl_win32.cpp
circle $PATHS $FLAGS bslmt_turnstile.cpp
circle $PATHS $FLAGS bslmt_writelockguard.cpp
